from __future__ import annotations

from typing import Any


def build_nist_context() -> dict[str, Any]:
    return {
        "framework": "NIST-oriented telemetry mapping for cryptographic monitoring",
        "mapping_chain": "control -> telemetry -> threshold -> alert/finding -> response input -> evidence",
        "controls": [
            {
                "control": "SI-4",
                "name": "System Monitoring",
                "telemetry_used": [
                    "Active TLS handshake success/failure tests",
                    "Latest CloudWatch CPU metric from AWS/EC2",
                    "Latest CloudWatch memory metric from CWAgent",
                    "Latest CloudWatch networking metrics from AWS/EC2",
                    "CloudWatch Logs JSON events generated by the C++ TLS application",
                ],
            },
            {
                "control": "AU-6",
                "name": "Audit Record Review, Analysis, and Reporting",
                "telemetry_used": [
                    "CloudWatch Logs JSON events",
                    "Aggregated success/failure metrics",
                    "TLS error categorization",
                    "Evidence retained in CloudWatch Log Groups",
                ],
            },
            {
                "control": "SC-13",
                "name": "Cryptographic Protection",
                "telemetry_used": [
                    "TLS group requested by active tests",
                    "TLS group observed in application logs",
                    "Cipher suite observed in application logs",
                    "Certificate signature algorithm observed in application logs",
                    "PQC booleans observed in application logs",
                ],
            },
            {
                "control": "SC-8",
                "name": "Transmission Confidentiality and Integrity",
                "telemetry_used": [
                    "TLS protocol negotiation through active tests",
                    "TLS protocol and cipher suite from CloudWatch Logs",
                    "Handshake success and failure behavior",
                ],
            },
            {
                "control": "CM-6",
                "name": "Configuration Settings",
                "telemetry_used": [
                    "Expected active test outcomes per endpoint",
                    "Observed crypto-agility behavior",
                ],
            },
        ],
    }


def evaluate_findings(report: dict[str, Any]) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []

    active_summary = report.get("active_tls_tests", {}).get("summary", {})
    mismatches = int(active_summary.get("expectation_mismatches", 0) or 0)
    if mismatches > 0:
        findings.append(
            _finding(
                control="SI-4/SC-13",
                severity="high",
                title="Active TLS test expectation mismatch",
                description=f"{mismatches} active TLS test(s) did not match the expected outcome.",
                threshold="expectation_mismatches == 0",
                recommended_action="Review endpoint TLS groups, certificate signature algorithms, and client compatibility.",
            )
        )

    logs_totals = report.get("cloudwatch_logs", {}).get("aggregated_metrics", {}).get("totals", {})
    failure_percent = float(logs_totals.get("failure_percent", 0.0) or 0.0)
    if failure_percent >= 30.0:
        findings.append(
            _finding(
                control="SI-4/AU-6",
                severity="medium",
                title="High TLS failure rate in CloudWatch Logs",
                description=f"TLS failure rate is {failure_percent}% in the selected lookback window.",
                threshold="failure_percent < 30",
                recommended_action="Investigate unsupported TLS groups, unsupported signature algorithms, and unexpected client behavior.",
            )
        )

    metrics = report.get("cloudwatch_metrics", {}).get("metrics", {})
    cpu = _metric_value(metrics, "cpu_utilization_percent")
    memory = _metric_value(metrics, "memory_used_percent")
    network_in = _metric_value(metrics, "network_in_bytes")
    network_out = _metric_value(metrics, "network_out_bytes")

    if cpu is not None and cpu >= 80.0:
        findings.append(
            _finding(
                control="SI-4",
                severity="high",
                title="High CPU utilization",
                description=f"CPUUtilization is {cpu}%.",
                threshold="CPUUtilization < 80%",
                recommended_action="Inspect container load, TLS handshake volume, and instance sizing.",
            )
        )

    if memory is not None and memory >= 80.0:
        findings.append(
            _finding(
                control="SI-4",
                severity="high",
                title="High memory utilization",
                description=f"mem_used_percent is {memory}%.",
                threshold="mem_used_percent < 80%",
                recommended_action="Inspect container memory usage and consider increasing instance size.",
            )
        )

    if cpu is None:
        findings.append(
            _finding(
                control="SI-4",
                severity="medium",
                title="CPU metric unavailable",
                description="CloudWatch did not return a recent CPUUtilization datapoint from AWS/EC2.",
                threshold="latest CPU datapoint exists",
                recommended_action="Validate EC2 monitoring, instance ID, region, CloudWatch permissions and selected lookback window.",
            )
        )

    if memory is None:
        findings.append(
            _finding(
                control="SI-4",
                severity="medium",
                title="Memory metric unavailable",
                description="CloudWatch Agent did not return a recent mem_used_percent datapoint from the CWAgent namespace.",
                threshold="latest memory datapoint exists",
                recommended_action="Validate CloudWatch Agent status, CWAgent namespace, InstanceId dimension and selected lookback window.",
            )
        )

    if network_in is None or network_out is None:
        findings.append(
            _finding(
                control="SI-4",
                severity="low",
                title="Network traffic metric unavailable",
                description="CloudWatch did not return recent NetworkIn and/or NetworkOut datapoints from AWS/EC2.",
                threshold="latest network datapoints exist",
                recommended_action="Validate EC2 metric availability and selected lookback window.",
            )
        )

    parsed_count = int(report.get("cloudwatch_logs", {}).get("parsed_event_count", 0) or 0)
    if parsed_count == 0:
        findings.append(
            _finding(
                control="AU-6/SI-4",
                severity="medium",
                title="No parseable TLS telemetry logs found in CloudWatch Logs",
                description="No JSON log events were collected from the configured CloudWatch Log Groups.",
                threshold="parsed CloudWatch log events > 0",
                recommended_action="Generate traffic, validate CloudWatch Agent status, log file paths, permissions, Log Group names and ingestion delay.",
            )
        )

    return findings


def _metric_value(metrics: dict[str, Any], metric_name: str) -> float | None:
    value = metrics.get(metric_name, {}).get("value")
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _finding(
    *,
    control: str,
    severity: str,
    title: str,
    description: str,
    threshold: str,
    recommended_action: str,
) -> dict[str, Any]:
    return {
        "control": control,
        "severity": severity,
        "title": title,
        "description": description,
        "threshold": threshold,
        "recommended_action": recommended_action,
    }
